<?php

/**
 * @file
 * Provides a timeEntry entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function test_exercice_theme() {
    return [
        'time_entry' => [
            'render element' => 'elements',
        ],
    ];
}

/**
 * Prepares variables for timeEntry templates.
 *
 * Default template: time-entry.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the timeEntry information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_time_entry(array &$variables) {
    foreach (Element::children($variables['elements']) as $key) {
        $variables['content'][$key] = $variables['elements'][$key];
    }
}
